import type {
  Opportunity,
  Review,
  Source,
  DashboardStats,
} from "./types";

export const mockOpportunities: Opportunity[] = [
  {
    id: "opp-001",
    title: "Manchester United Away Trip - Champions League",
    description:
      "Large group of supporters looking for organized travel to Barcelona for the Champions League quarterfinal. Active discussion with 250+ interested members.",
    type: "fan-travel",
    status: "new",
    complianceStatus: "verified",
    source: "reddit",
    sourceUrl: "https://reddit.com/r/reddevils/comments/xyz",
    location: "Barcelona, Spain",
    eventDate: "2026-04-15",
    groupSize: 250,
    estimatedRevenue: 125000,
    confidence: 92,
    createdAt: "2026-03-10T08:30:00Z",
    updatedAt: "2026-03-14T10:15:00Z",
    tags: ["football", "champions-league", "europe"],
  },
  {
    id: "opp-002",
    title: "Taylor Swift Eras Tour - Vienna Demand Surge",
    description:
      "Massive demand detected for Taylor Swift Vienna dates. Multiple forum threads with 500+ potential travelers from UK seeking group packages.",
    type: "concert-demand",
    status: "under-review",
    complianceStatus: "pending",
    source: "twitter",
    sourceUrl: "https://twitter.com/swifties_uk/status/123",
    location: "Vienna, Austria",
    eventDate: "2026-06-20",
    groupSize: 500,
    estimatedRevenue: 200000,
    confidence: 88,
    createdAt: "2026-03-08T14:20:00Z",
    updatedAt: "2026-03-13T16:45:00Z",
    assignedTo: "Sarah Chen",
    tags: ["music", "pop", "europe"],
  },
  {
    id: "opp-003",
    title: "Liverpool FC Supporters Club - Madrid Final",
    description:
      "Official supporters club organizing charter flights and accommodation for potential Champions League final in Madrid.",
    type: "supporter-trip",
    status: "approved",
    complianceStatus: "verified",
    source: "facebook",
    sourceUrl: "https://facebook.com/groups/lfcsupporters",
    location: "Madrid, Spain",
    eventDate: "2026-05-28",
    groupSize: 180,
    estimatedRevenue: 90000,
    confidence: 95,
    createdAt: "2026-03-05T09:00:00Z",
    updatedAt: "2026-03-12T11:30:00Z",
    assignedTo: "Mike Johnson",
    tags: ["football", "champions-league", "charter"],
  },
  {
    id: "opp-004",
    title: "Mentawai Islands Surf Camp Group",
    description:
      "Experienced surfers seeking group charter boat trip to Mentawai Islands. Discussion shows 40 confirmed interested surfers for 2-week expedition.",
    type: "surf-trip",
    status: "new",
    complianceStatus: "verified",
    source: "forum",
    sourceUrl: "https://magicseaweed.com/forum/thread/456",
    location: "Mentawai Islands, Indonesia",
    eventDate: "2026-07-10",
    groupSize: 40,
    estimatedRevenue: 80000,
    confidence: 85,
    createdAt: "2026-03-11T12:00:00Z",
    updatedAt: "2026-03-14T08:00:00Z",
    tags: ["surfing", "adventure", "asia"],
  },
  {
    id: "opp-005",
    title: "British Expats Portugal Relocation Group",
    description:
      "Growing community of UK expats planning group viewing trips to Algarve region. Regular monthly trips with 30-50 participants.",
    type: "expat-travel",
    status: "under-review",
    complianceStatus: "pending",
    source: "facebook",
    sourceUrl: "https://facebook.com/groups/britsinportugal",
    location: "Algarve, Portugal",
    eventDate: "2026-04-01",
    groupSize: 45,
    estimatedRevenue: 22500,
    confidence: 78,
    createdAt: "2026-03-09T15:30:00Z",
    updatedAt: "2026-03-13T09:20:00Z",
    assignedTo: "Emma Williams",
    tags: ["expat", "relocation", "europe"],
  },
  {
    id: "opp-006",
    title: "Corporate Golf Tournament Charter - Dubai",
    description:
      "Tech company seeking charter flight for 120 employees to Dubai for annual golf tournament and team building event.",
    type: "charter",
    status: "approved",
    complianceStatus: "verified",
    source: "discord",
    sourceUrl: "https://discord.gg/techgolf",
    location: "Dubai, UAE",
    eventDate: "2026-05-15",
    groupSize: 120,
    estimatedRevenue: 180000,
    confidence: 97,
    createdAt: "2026-03-06T10:45:00Z",
    updatedAt: "2026-03-11T14:00:00Z",
    assignedTo: "David Brown",
    tags: ["corporate", "golf", "charter", "middle-east"],
  },
  {
    id: "opp-007",
    title: "Coldplay World Tour - Singapore Fanbase",
    description:
      "SEA Coldplay fans coordinating group travel to Singapore for upcoming tour dates. Multiple telegram groups with combined 800+ members.",
    type: "concert-demand",
    status: "new",
    complianceStatus: "flagged",
    source: "telegram",
    sourceUrl: "https://t.me/coldplayasia",
    location: "Singapore",
    eventDate: "2026-08-12",
    groupSize: 800,
    estimatedRevenue: 320000,
    confidence: 72,
    createdAt: "2026-03-12T07:15:00Z",
    updatedAt: "2026-03-14T06:30:00Z",
    tags: ["music", "rock", "asia"],
  },
  {
    id: "opp-008",
    title: "Celtic FC Europa League Away Days",
    description:
      "Celtic supporters organizing multiple away trips for Europa League group stages. Established travel club with reliable booking history.",
    type: "supporter-trip",
    status: "approved",
    complianceStatus: "verified",
    source: "twitter",
    sourceUrl: "https://twitter.com/celtictravel",
    location: "Various European Cities",
    eventDate: "2026-09-01",
    groupSize: 200,
    estimatedRevenue: 100000,
    confidence: 91,
    createdAt: "2026-03-04T13:00:00Z",
    updatedAt: "2026-03-10T17:45:00Z",
    assignedTo: "Sarah Chen",
    tags: ["football", "europa-league", "europe"],
  },
  {
    id: "opp-009",
    title: "Bali Surf Retreat - Intermediate Group",
    description:
      "Surf school organizing intermediate level group trip to Bali. 60 confirmed participants seeking accommodation and transport package.",
    type: "surf-trip",
    status: "rejected",
    complianceStatus: "unknown",
    source: "instagram",
    sourceUrl: "https://instagram.com/p/surfbali",
    location: "Bali, Indonesia",
    eventDate: "2026-06-05",
    groupSize: 60,
    estimatedRevenue: 45000,
    confidence: 65,
    createdAt: "2026-03-07T16:20:00Z",
    updatedAt: "2026-03-09T12:00:00Z",
    tags: ["surfing", "beginner", "asia"],
  },
  {
    id: "opp-010",
    title: "American Expats Spain - Costa del Sol",
    description:
      "US expat community in Spain organizing quarterly property viewing tours along Costa del Sol. Consistent demand with repeat customers.",
    type: "expat-travel",
    status: "under-review",
    complianceStatus: "verified",
    source: "facebook",
    sourceUrl: "https://facebook.com/groups/americansinspain",
    location: "Costa del Sol, Spain",
    eventDate: "2026-04-20",
    groupSize: 35,
    estimatedRevenue: 17500,
    confidence: 82,
    createdAt: "2026-03-10T11:00:00Z",
    updatedAt: "2026-03-13T15:30:00Z",
    tags: ["expat", "relocation", "europe"],
  },
];

export const mockReviews: Review[] = [
  {
    id: "rev-001",
    opportunityId: "opp-002",
    opportunityTitle: "Taylor Swift Eras Tour - Vienna Demand Surge",
    reviewer: "Sarah Chen",
    status: "pending",
    notes: "Awaiting confirmation of venue capacity and date availability.",
    createdAt: "2026-03-13T10:00:00Z",
  },
  {
    id: "rev-002",
    opportunityId: "opp-003",
    opportunityTitle: "Liverpool FC Supporters Club - Madrid Final",
    reviewer: "Mike Johnson",
    status: "approved",
    notes: "Verified with official supporters club. Charter pricing confirmed.",
    createdAt: "2026-03-12T14:30:00Z",
  },
  {
    id: "rev-003",
    opportunityId: "opp-005",
    opportunityTitle: "British Expats Portugal Relocation Group",
    reviewer: "Emma Williams",
    status: "pending",
    notes: "Need to verify group organizer credentials and payment history.",
    createdAt: "2026-03-13T09:15:00Z",
  },
  {
    id: "rev-004",
    opportunityId: "opp-006",
    opportunityTitle: "Corporate Golf Tournament Charter - Dubai",
    reviewer: "David Brown",
    status: "approved",
    notes: "Corporate client verified. Contract signed and deposit received.",
    createdAt: "2026-03-11T16:00:00Z",
  },
  {
    id: "rev-005",
    opportunityId: "opp-009",
    opportunityTitle: "Bali Surf Retreat - Intermediate Group",
    reviewer: "Mike Johnson",
    status: "rejected",
    notes: "Group size too small for charter. Redirected to partner agency.",
    createdAt: "2026-03-09T11:45:00Z",
  },
];

export const mockSources: Source[] = [
  {
    id: "src-001",
    name: "Reddit Sports Travel",
    type: "reddit",
    status: "active",
    lastSync: "2026-03-14T09:00:00Z",
    opportunitiesFound: 156,
    url: "https://reddit.com/r/sportstravel",
  },
  {
    id: "src-002",
    name: "Twitter Fan Groups",
    type: "twitter",
    status: "active",
    lastSync: "2026-03-14T09:15:00Z",
    opportunitiesFound: 89,
    url: "https://twitter.com/search",
  },
  {
    id: "src-003",
    name: "Facebook Travel Groups",
    type: "facebook",
    status: "active",
    lastSync: "2026-03-14T08:45:00Z",
    opportunitiesFound: 234,
    url: "https://facebook.com/groups",
  },
  {
    id: "src-004",
    name: "Instagram Travel Tags",
    type: "instagram",
    status: "paused",
    lastSync: "2026-03-12T14:00:00Z",
    opportunitiesFound: 45,
    url: "https://instagram.com/explore/tags",
  },
  {
    id: "src-005",
    name: "Magic Seaweed Forums",
    type: "forum",
    status: "active",
    lastSync: "2026-03-14T07:30:00Z",
    opportunitiesFound: 67,
    url: "https://magicseaweed.com/forum",
  },
  {
    id: "src-006",
    name: "Discord Travel Servers",
    type: "discord",
    status: "active",
    lastSync: "2026-03-14T09:30:00Z",
    opportunitiesFound: 112,
    url: "https://discord.com/servers",
  },
  {
    id: "src-007",
    name: "Telegram Groups Monitor",
    type: "telegram",
    status: "error",
    lastSync: "2026-03-13T22:00:00Z",
    opportunitiesFound: 78,
    url: "https://telegram.org",
  },
];

export const mockDashboardStats: DashboardStats = {
  totalOpportunities: 847,
  newThisWeek: 124,
  pendingReview: 38,
  approvedThisMonth: 67,
  estimatedRevenue: 2850000,
  avgConfidence: 84,
};
